# Generated by Django 3.2.12 on 2022-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220305_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.CharField(max_length=20),
        ),
    ]
