# Generated by Django 3.2.12 on 2022-03-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
